# Generated by Django 2.1 on 2018-08-06 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('cover', models.ImageField(upload_to='covers/')),
                ('printed_year', models.PositiveSmallIntegerField()),
                ('score', models.DecimalField(decimal_places=1, default=0, max_digits=1)),
                ('authors', models.ManyToManyField(related_name='books', to='market.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(choices=[('★☆☆☆☆', 1), ('★★☆☆☆', 2), ('★★★☆☆', 3), ('★★★★☆', 4), ('★★★★★', 5)])),
                ('title', models.CharField(max_length=180)),
                ('content', models.CharField(max_length=900)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='market.Customer'),
        ),
        migrations.AddField(
            model_name='comment',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='market.Book'),
        ),
        migrations.AddField(
            model_name='book',
            name='holders',
            field=models.ManyToManyField(related_name='books', to='market.Customer'),
        ),
        migrations.AddField(
            model_name='book',
            name='shoppers',
            field=models.ManyToManyField(related_name='shopping_cart', to='market.Customer'),
        ),
    ]
