# Generated by Django 2.1 on 2018-08-08 12:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20180806_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='reg_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activationlinks',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='market.Customer'),
        ),
    ]
