# Generated by Django 2.1 on 2018-08-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_auto_20180808_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.PositiveIntegerField(default=500),
            preserve_default=False,
        ),
    ]
