# Generated by Django 2.1 on 2018-08-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_auto_20180811_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='score',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
